### ISSUE TITLE
Ability to translate most of parts of the plugin

### ISSUE THREAD

**Issue by pavlo-tk** [ebussola/octobercms-feedback#7]
Hello Leonardo.
Now the "Feedback" plugin is translated partially, in many places english labels are harcoded.

Are you planning some update on this case?
If not — tell me, and i will create a pull request for this.

**Comment by shina** [comment]
Hello, it is on the plan.
However, I don't know when I'll be able to do it.

So, if you want to create a pull request, it will be very helpful!

**Comment by pavlo-tk** [comment]
Working on that...
